services:
  postgres:
    image: postgres:15
    container_name: algorithmx-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant
    container_name: algorithmx-qdrant
    ports:
      - "${QDRANT_PORT}:6333"
    restart: unless-stopped

  backend:
    build:
      context: .  # path to FastAPI folder
      dockerfile: Dockerfile_fastapi
    container_name: algorithmx-fastapi
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      QDRANT_URL: http://qdrant:${QDRANT_PORT}
      MODEL_NAME: ${MODEL_NAME}
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      - postgres
      - qdrant
    restart: unless-stopped

  frontend:
    build:
      context: .  # path to Streamlit folder
      dockerfile: Dockerfile_streamlit
    container_name: algorithmx-streamlit
    environment:
      BACKEND_URL: http://backend:${BACKEND_PORT}
    ports:
      - "${FRONTEND_PORT}:8501"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
